---
experiment:
  pipeline: Pooled Cell Painting
  project_tag: 2018_11_20_Periscope_Calico
  batches:
    - 20240202_6W_CP498_SABER_Pilot_HeLa
  plates:
    - SABER_Plate_1
    - SABER_Plate_2
    - SABER_Plate_3
  wells:
    setallwells:
      - Well1
      - Well2
      - Well3
      - Well4
      - Well5
      - Well6
  split:
    qc:
      batches: false
      plates: true
      wells: false
    profile:
      batches: false
      plates: true
      wells: false
  barcoding_cycles: 12
  sites_per_image_grid_side: 10
  control_barcode_ids:
    - nontargeting
---
directory_structure:
  input_data_dir: /home/ubuntu/bucket/projects/2018_11_20_Periscope_Calico/workspace/analysis
  batch_id_folder: true
  output_data_dir: data/
  preprocess:
    base: 0.site-qc/
    batch_id_folder: true
    spots: spots/
    paint: paint/
    data: data/
    results: results/
    figures: figures/
  profile:
    base: 1.profiles/
    batch_id_folder: true
    single_cell: single_cell/
    profiles: profiles/
